[package]
name = "Drone"
version = "0.1.0"
authors = ["Jongwhan Lee <jonghwan@crypto.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
